### ISSUE TITLE
A suggestion and more

### ISSUE THREAD

**Issue by JoaoPedroDinis** [OfficeDev/Excel-IO#3]
As I don't have much experience, I'll leave here images of code I've done and that certainly could be improved upon on things that I had to implement to create an azure storage table exporter and importer to excel that I'm working on:

![image](https://user-images.githubusercontent.com/72220355/94878864-91845700-0456-11eb-8635-771ce3508267.png)

In this ExcelConverter.cs method I've added CellReference with this quick fix workaround and to cells as well:
![image](https://user-images.githubusercontent.com/72220355/94879009-eaec8600-0456-11eb-93e7-d8f8a5771ee2.png)

To support dates I've done: 
![image](https://user-images.githubusercontent.com/72220355/94880139-1624a480-045a-11eb-8e23-85ff16a001d1.png)

Then I changed GetCellValue to convert DateTime? values present on azure storage table 
![image](https://user-images.githubusercontent.com/72220355/94880016-c3e38380-0459-11eb-9a03-87355190680c.png)

and in ReadSheet<T> I checked for type names that contain data to parse the string to appropriate type
![image](https://user-images.githubusercontent.com/72220355/94871802-ce465300-0442-11eb-9d3f-98f7b2f9f6fb.png)

As for my suggestion:  This would be great in a Nuget package

**Comment by craigomatic** [comment]
Thanks for posting this!

From your screenshots I see you've added support for dates and it looks like you also fixed a bug with columns after Z?

I'll write some tests and merge your work in, or if you'd like you can submit a PR?

Yes I agree with you re the NuGet package for this library. I will revisit the process and see if we can make this happen sooner rather than later.

**Comment by JoaoDinisCodit** [comment]
Sorry for the late reply I've been a little busy lately and yes I can submit a PR 👍
